**Step1: Importing the required Libraries**

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.classifier import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

**Step 2: Loading the Dataset**

In [5]:
df = pd.read_csv("Data/heart.csv")

In [6]:
X = df.drop('target', axis=1)
y = df['target']

In [7]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

**Step 3: Splitting the Data into Training and Testing Sets**

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

**Step 4: Standardizing the Data**

In [10]:
sc = StandardScaler()
var_transform = ['thalach','age','trestbps','oldpeak','chol']
X_train[var_transform] = sc.fit_transform(X_train[var_transform])
X_test[var_transform] = sc.transform(X_test[var_transform])

In [11]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
835,-0.585840,1,2,-0.779454,-1.935031,0,0,-1.019094,0,-0.210661,2,3,2
137,1.051477,0,0,2.741732,1.610634,0,1,0.202882,1,-0.912152,2,0,2
534,-0.040068,0,2,-1.347387,0.442176,0,0,0.770228,0,-0.912152,2,0,2
495,0.505705,1,0,0.186033,-0.222636,0,1,0.508376,0,-0.473720,1,0,3
244,-0.367531,1,2,-0.381900,-0.001032,1,0,0.726586,0,1.192321,1,0,2

**Step 5: Building First Layer Estimators**

In [15]:
KNC = KNeighborsClassifier()
NB = GaussianNB()

**Step 6: Training and Evaluating KNeighborsClassifier**

In [19]:
model_Knc = KNC.fit(X_train, y_train)
pred_Knc = model_Knc.predict(X_test)
acc_Knc = accuracy_score(y_test, pred_Knc)
print("Accuracy Score of KNeighbours Classifier:", acc_Knc*100)

Accuracy Score of KNeighbours Classifier: 51.21951219512195

**Step 7: Training and Evaluating Naive Bayes Classifier**

In [21]:
model_NB = NB.fit(X_train, y_train)
pred_NB = model_NB.predict(X_test)
acc_nb = accuracy_score(y_test, pred_NB)
print("Accuracy of Naive Bayes Classifier:", acc_nb*100)

Accuracy of Naive Bayes Classifier: 49.75609756097561

**Step 8: Implementing the Stacking Classifier**

In [23]:
base_learners = [
    KNeighborsClassifier(),
    GaussianNB()
]
meta_model = LogisticRegression()
stacking_model = StackingClassifier(classifiers=base_learners, meta_classifier=meta_model, use_probas=True)

**Step 9: Training Stacking Classifier**

In [25]:
model_stack = stacking_model.fit(X_train, y_train)
pred_stack = model_stack.predict(X_test)
acc_stack = accuracy_score(y_test, pred_stack)
print("Accuracy Score of Stacked Model:", acc_stack*100)

Accuracy Score of Stacked Model: 51.21951219512195